CREATE DATABASE IF NOT EXISTS MyDataBase;
USE MyDataBase;

CREATE TABLE IF NOT EXISTS MyGuests (
    Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR(30) NOT NULL,
    lastname VARCHAR(30) NOT NULL,
    email VARCHAR(50),
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Comments (
    Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    post_Id INT(6) UNSIGNED,
    firstname VARCHAR(30) NOT NULL,
    comment TEXT,
    comment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
